---
title: "Research"
listing: 
  contents: research
  type: default # or `default` or `table`; each type has its own set of yaml options to include
  sort: "date desc" # can also sort on more than one field
  #categories: true # allows you to sort posts by assigned categories 
---

Having the opportunity to collaborate with experts in a wide variety of fields is my favorite part of being a statistician. As I develop as a researcher, my goal is to contribute work that helps understand and solve complex interdisciplinary problems.

## Current Projects

1. I am advised by [Will Townes](https://willtownes.github.io/) and am part of the CMU [Delphi group](https://delphi.cmu.edu/). My current research is centered around statistical methods for wastewater-based epidemiology. 

2. Previously, I worked with [Weijing Tang](https://sites.google.com/andrew.cmu.edu/weijingtang/home?authuser=0) and [Phoebe Lam](https://www.lshlab.org/) on a year-long collaboration titled [Stress and Cold Susceptibility: Comparing Z-Score and Latent Measurement Models](research/erinfranke_finalADA.pdf). We are currently working on a continuation of this research that takes further steps to compare the effectiveness of moderated nonlinear factor analysis with commonly used standardization approaches for psychology research. *Manuscript in progress (as of May 2026)*.

3. On the side, I've done a little bit of sports analytics research. This summer, I'll be presenting my work on super shoes and elite marathoning at [JSM](https://ww3.aievolution.com/JSMAnnual2026/index.cfm?do=ev.viewEv&ev=5434).

4. Check out my [Teaching](https://efranke22.github.io/teaching.html) page to learn more about my teaching-related research!








